const header=document.querySelector('[data-header]'),toggle=document.querySelector('[data-menu-toggle]'),menu=document.querySelector('[data-menu]'),modal=document.querySelector('[data-modal]');
const updateHeader=()=>header.classList.toggle('scrolled',scrollY>12);updateHeader();addEventListener('scroll',updateHeader,{passive:true});
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));menu.classList.toggle('open',!open)});
menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');menu.classList.remove('open')}));
menu.querySelector('a[href="#orienta"]')?.remove();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));
document.querySelector('[data-close]').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});
const demos=[
  {category:'Projetos',title:'Painel de Projetos',problem:'Exemplo demonstrativo de um contexto em que é preciso reunir iniciativas e prioridades em uma visão única.',description:'Exemplo de uma ferramenta para apoiar o acompanhamento de projetos.',how:'Exemplo de explicação sobre como as informações poderiam ser organizadas e consultadas.',features:['Visão de iniciativas','Acompanhamento de etapas','Organização de prioridades']},
  {category:'Processos',title:'Fluxo de Processos',problem:'Exemplo demonstrativo de um contexto em que as etapas de um processo precisam ser visualizadas.',description:'Exemplo de uma ferramenta de apoio ao mapeamento de processos.',how:'Exemplo de explicação sobre como fluxos e pontos de atenção poderiam ser apresentados.',features:['Visão de fluxo','Etapas organizadas','Pontos de atenção']},
  {category:'Documentação',title:'Central de Documentos',problem:'Exemplo demonstrativo de organização e consulta de informações importantes.',description:'Exemplo de uma ferramenta para centralizar documentação.',how:'Exemplo de explicação sobre como documentos poderiam ser estruturados para consulta.',features:['Documentos centralizados','Busca organizada','Acesso simplificado']},
  {category:'Indicadores',title:'Visão de Indicadores',problem:'Exemplo demonstrativo de acompanhamento de informações relevantes à operação.',description:'Exemplo de uma ferramenta de visualização de indicadores.',how:'Exemplo de explicação sobre como tendências e informações poderiam ser acompanhadas.',features:['Leitura de indicadores','Visão de tendências','Apoio à decisão']},
  {category:'Operação',title:'Checklist Operacional',problem:'Exemplo demonstrativo de uma rotina que precisa de maior padronização.',description:'Exemplo de uma ferramenta de apoio à execução de atividades.',how:'Exemplo de explicação sobre como listas de verificação poderiam ser utilizadas.',features:['Rotinas organizadas','Itens de verificação','Padronização']},
  {category:'Governança',title:'Matriz de Riscos',problem:'Exemplo demonstrativo de identificação e acompanhamento de riscos.',description:'Exemplo de uma ferramenta para dar visibilidade a riscos e prioridades.',how:'Exemplo de explicação sobre como os riscos poderiam ser estruturados e acompanhados.',features:['Mapeamento de riscos','Priorização','Acompanhamento']}
];
const cards=[...document.querySelectorAll('.project-card')];
const grid=document.querySelector('.project-grid');
if(cards[1]&&cards[2]){grid.insertBefore(cards[2],cards[1]);[demos[1],demos[2]]=[demos[2],demos[1]]}
const modelos={category:'Documentação',title:'Gerador de Modelos',problem:'Padronizar a identificação de normas e procedimentos.',description:'Gere documentos padronizados a partir do tipo de documento, área responsável e versão.',how:'O usuário informa os dados do documento e o modelo organiza automaticamente as informações do cabeçalho.',features:['Tipo de documento','Área responsável','Controle de versão'],url:'gerador-de-modelos/'};
const ged={category:'Documentação',title:'Gestão Documental',problem:'Organizar documentos, revisões, alertas e informações essenciais em uma base única.',description:'Acompanhe documentos, prazos de revisão, validade, histórico e indicadores em uma interface de gestão documental.',how:'O usuário pode cadastrar documentos, consultar detalhes, controlar revisões, importar e exportar dados e acompanhar alertas diretamente no navegador.',features:['Cadastro e consulta de documentos','Revisões, validades e alertas','Importação e exportação de dados'],url:'gestao-documental/'};
demos[0]=modelos;
demos[1]=ged;
if(cards[0]){cards[0].querySelector('.project-category').textContent=modelos.category;cards[0].querySelector('h3').textContent=modelos.title;cards[0].querySelector('.project-summary').textContent='Gere documentos padronizados com cabeçalho automatizado.'}
if(cards[2]){cards[2].querySelector('.project-category').textContent=ged.category;cards[2].querySelector('h3').textContent=ged.title;cards[2].querySelector('.project-summary').textContent='Organize documentos, revisões e alertas em uma base única.';cards[2].querySelector('.project-preview').style.backgroundImage="url('ged-capa.png')";cards[2].querySelector('.project-preview').style.backgroundSize='cover';cards[2].querySelector('.project-preview').style.backgroundPosition='center'}
document.querySelectorAll('.project-card').forEach(card=>card.style.minHeight='310px');
document.querySelectorAll('.portrait>div,.portrait p,.button,.contact-link,.panel,.project-card,.empty,.tags span,.project-icon,.guide>span,dialog,.modal,.brand b').forEach(element=>element.style.borderRadius='14px');
document.querySelectorAll('a[href*="CV%20Ubirajara"]').forEach(link=>{link.removeAttribute('download');link.target='_blank';link.rel='noopener noreferrer'});
const openProject=(card,project)=>{modal.querySelector('[data-category]').textContent=project.category;modal.querySelector('[data-title]').textContent=project.title;modal.querySelector('[data-problem]').textContent=project.problem;modal.querySelector('[data-description]').textContent=project.description;modal.querySelector('[data-how]').textContent=project.how;const preview=modal.querySelector('[data-modal-preview]');preview.style.backgroundImage=getComputedStyle(card.querySelector('.project-preview')).backgroundImage;preview.style.backgroundColor='#e7f1f1';preview.style.backgroundSize='contain';preview.style.backgroundPosition='center';preview.style.backgroundRepeat='no-repeat';const list=modal.querySelector('[data-features]');list.replaceChildren(...project.features.map(text=>Object.assign(document.createElement('li'),{textContent:text})));const openLink=modal.querySelector('[data-url]');openLink.href=project.url||'#';openLink.textContent='Abrir ferramenta →';openLink.style.display='flex';openLink.style.width='fit-content';openLink.style.marginLeft='auto';openLink.target='_blank';openLink.rel='noopener noreferrer';modal.querySelector('[data-download]')?.remove();modal.showModal()};
document.querySelectorAll('.project-card').forEach((card,index)=>{card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Conhecer projeto demonstrativo: ${demos[index].title}`);card.addEventListener('click',()=>openProject(card,demos[index]));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openProject(card,demos[index])}})});
document.querySelector('[data-year]').textContent=new Date().getFullYear();
